### ISSUE TITLE
maven warnings

### ISSUE THREAD

**Issue by ktabe** [piax/piax#10]
I got the following warnings when invoking maven.

> % mvn -Dmaven.test.skip=true clean package
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for org.piax:piax-agent:jar:3.1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 48, column 15
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for org.piax:piax-gtrans:jar:3.1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 49, column 15
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for org.piax:piax-gtrans-dtn:jar:3.1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 48, column 15
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for org.piax:piax-dht:jar:3.1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 42, column 15
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]

**Comment by teranisi** [comment]
I think it is fixed now.

**Comment by ktabe** [comment]
confirmed.
